title: RA_2602_list_accounts
id: RA2602
description: >
  List accounts on a particular system
author: Andreas Hunkeler/@Karneades
creation_date: 2021/05/21
stage: identification
automation:
  - thehive
references:
  - https://example.com
workflow: |
  List accounts on a particular system or on all of your systems.
  This could be done using system tools or reading account configuration.
  
  * Linux: cat /etc/shadows
  * Windows: net user
  * Or using artifact collection tools to get an account listing
