title: RA_2602_list_accounts
id: RA2602
description: >
  List accounts on a particular system
author: Andreas Hunkeler/@Karneades
creation_date: 2021/05/21
stage: identification
automation:
  - thehive
references:
  - https://example.com
workflow: |
  List accounts on a particular system to get an overview of 
  the available accounts.
